module.exports = {
	PARAM_MISSING: 422,
	PARAM_MISSING_MSG: 'Require parameter missing',
	NO_DATA: 400,
	NO_DATA_FOUND: 'No data found',
	NO_USER_FOUND: 'User not found',
	INVALID_USER: 'Not a valid user',
	USER_ALREADY_EXIST: 'User already exist with mobile or email',
	SUCCESS: 200,
	SUCCESS_MSG: 'Success',
	QUERY_ERROR: 500,
	QUERY_ERROR_MSG: 'Something Went wrong',
	INVALID_CREDENTIAL: 401,
	INVALID_CREDENTIAL_MSG: 'Invalid credential. Please try again.',
	UNAUTHORIZE: 401,
	UNAUTHORIZE_MSG: 'Unauthorize User',
	BAD_REQUEST: 400,
	BAD_REQUEST_MSG: 'Entered data is Invalid',
	INCORRECT_EMAIL: 'Incorrect email',
	INCORRECT_PASSWORD: 'Incorrect current password',
	INCORRECT_MOBILE: 'Incorrect mobile',
};
